obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[-0.2, -0.2], [-0.2, 0.2], [0.2, 0.2], [0.2, -0.2]] # Ajusta según las dimensiones de tu robot
inflation_radius: 0.3 # Ajusta según la distancia de seguridad deseada

transform_tolerance: 0.2
update_frequency: 5.0
publish_frequency: 2.0

plugins:
  - {name: obstacles, type: "costmap_2d::ObstacleLayer"}
  - {name: inflation, type: "costmap_2d::InflationLayer"}

obstacles:
  observation_sources: laser_scan_sensor
  laser_scan_sensor: {topic: /scan, sensor_frame: laser_frame, data_type: LaserScan, expected_update_rate: 10.0, clearing: true, marking: true, min_obstacle_height: 0.0, max_obstacle_height: 2.0}