ekf_localization:
  frequency: 50.0
  two_d_mode: false
  publish_tf: true
  odom_frame_id: odom
  base_link_frame_id: base_link
  world_frame_id: odom

  odom0: encoder_odom
  odom0_config: [true, true, false,
                 false, false, true,
                 false, false, false,
                 false, false, false,
                 false, false, false]
  odom0_differential: false
  odom0_relative: false
  odom0_queue_size: 10
  odom0_pose_rejection_threshold: 0.5
  odom0_twist_rejection_threshold: 0.5

  imu0: /imu/data_raw
  imu0_config: [false, false, false,
                 true,  true,  true,
                 false, false, false,
                 true,  true,  true,
                 false, false, false]
  imu0_differential: false
  imu0_relative: false
  imu0_queue_size: 10
  imu0_pose_rejection_threshold: 0.8
  imu0_twist_rejection_threshold: 0.8

  process_noise_covariance: [0.05, 0,    0,    0,    0,    0,
                             0,    0.05, 0,    0,    0,    0,
                             0,    0,    0.06, 0,    0,    0,
                             0,    0,    0,    0.03, 0,    0,
                             0,    0,    0,    0,    0.03, 0,
                             0,    0,    0,    0,    0,    0.06]

  initial_state: [0, 0, 0,
                  0, 0, 0,
                  0, 0, 0,
                  0, 0, 0,
                  0, 0, 0]